classDiagram
  class ARForecaster {
    predictor
    predicts_std : bool
    forward(init_states: torch.Tensor, forcing_features: torch.Tensor, boundary_states: torch.Tensor) tuple[torch.Tensor, torch.Tensor | None]
  }
  class BaseGraphModel {
    encoding_grid_mlp : Sequential
    g2m_edges
    g2m_embedder : Sequential
    g2m_gnn : InteractionNet
    g2m_gnn_type : str
    grid_embedder : Sequential
    grid_input_dim
    hidden_dim : int
    hidden_layers : int
    hierarchical
    m2g_edges
    m2g_embedder : Sequential
    m2g_gnn : InteractionNet
    m2g_gnn_type : str
    mesh_aggr : str
    mlp_blueprint_end : list
    num_mesh_nodes
    output_map : Sequential
    processor_layers : int
    embedd_mesh_nodes()*
    forward(prev_state, prev_prev_state, forcing)
    get_num_mesh()*
    process_step(mesh_rep)*
  }
  class BaseHiGraphModel {
    level_mesh_sizes
    mesh_down_embedders : ModuleList
    mesh_down_gnn_type : str
    mesh_embedders : ModuleList
    mesh_init_gnns : ModuleList
    mesh_read_gnns : ModuleList
    mesh_same_embedders : ModuleList
    mesh_up_embedders : ModuleList
    mesh_up_gnn_type : str
    num_levels
    embedd_mesh_nodes()
    get_num_mesh()
    hi_processor_step(mesh_rep_levels, mesh_same_rep, mesh_up_rep, mesh_down_rep)*
    process_step(mesh_rep)
  }
  class Forecaster {
    predicts_std : bool
    forward(init_states: torch.Tensor, forcing_features: torch.Tensor, boundary_states: torch.Tensor)* tuple[torch.Tensor, torch.Tensor | None]
  }
  class ForecasterModule {
    create_gif : bool
    datastore : BaseDatastore
    forcing_mean : NoneType
    forcing_mean_tiled
    forcing_std : NoneType
    forcing_std_tiled
    forecaster
    loss
    matched_metrics : set
    n_example_pred : int
    per_var_std : NoneType
    plotted_examples : int
    restore_opt : bool
    spatial_loss_maps : list[Any]
    test_metrics : dict[str, list]
    time_step_int : int
    time_step_unit : str
    val_metrics : dict[str, list]
    aggregate_and_plot_metrics(metrics_dict, prefix)
    all_gather_cat(tensor_to_gather)
    common_step(batch)
    configure_optimizers()
    create_metric_log_dict(metric_tensor, prefix, metric_name)
    on_after_batch_transfer(batch, dataloader_idx)
    on_load_checkpoint(checkpoint)
    on_test_epoch_end()
    on_validation_epoch_end()
    plot_examples(batch, n_examples, split, prediction)
    test_step(batch, batch_idx)
    training_step(batch)
    validation_step(batch, batch_idx)
  }
  class GraphLAM {
    m2m_embedder : Sequential
    mesh_embedder : Sequential
    processor
    embedd_mesh_nodes()
    get_num_mesh()
    process_step(mesh_rep)
  }
  class HiLAM {
    mesh_down_gnns : ModuleList
    mesh_down_same_gnns : ModuleList
    mesh_up_gnns : ModuleList
    mesh_up_same_gnns : ModuleList
    hi_processor_step(mesh_rep_levels, mesh_same_rep, mesh_up_rep, mesh_down_rep)
    make_down_gnns()
    make_same_gnns()
    make_up_gnns()
    mesh_down_step(mesh_rep_levels, mesh_same_rep, mesh_down_rep, down_gnns, same_gnns)
    mesh_up_step(mesh_rep_levels, mesh_same_rep, mesh_up_rep, up_gnns, same_gnns)
  }
  class HiLAMParallel {
    edge_split_sections
    processor
    hi_processor_step(mesh_rep_levels, mesh_same_rep, mesh_up_rep, mesh_down_rep)
  }
  class StepPredictor {
    clamp_lower
    clamp_lower_upper
    clamp_upper
    grid_output_dim
    inverse_clamp_lower
    inverse_clamp_lower_upper
    inverse_clamp_upper
    num_grid_nodes
    output_std : bool
    predicts_std : bool
    expand_to_batch(x: torch.Tensor, batch_size: int) torch.Tensor
    forward(prev_state: torch.Tensor, prev_prev_state: torch.Tensor, forcing: torch.Tensor)* tuple[torch.Tensor, torch.Tensor | None]
    get_clamped_new_state(state_delta, prev_state)
    prepare_clamping_params(datastore: BaseDatastore)
  }
  ARForecaster --|> Forecaster
  BaseGraphModel --|> StepPredictor
  GraphLAM --|> BaseGraphModel
  HiLAM --|> BaseHiGraphModel
  HiLAMParallel --|> BaseHiGraphModel
  BaseHiGraphModel --|> BaseGraphModel
  Forecaster --o ForecasterModule : forecaster
  StepPredictor --o ARForecaster : predictor
