classDiagram
  class models {
  }
  class forecasters {
  }
  class autoregressive {
  }
  class base {
  }
  class module {
  }
  class step_predictors {
  }
  class base {
  }
  class graph {
  }
  class base {
  }
  class graph_lam {
  }
  class hi_lam {
  }
  class hi_lam_parallel {
  }
  class hierarchical {
  }
  models --> autoregressive
  models --> base
  models --> module
  models --> base
  models --> base
  models --> graph_lam
  models --> hi_lam
  models --> hi_lam_parallel
  models --> hierarchical
  forecasters --> autoregressive
  forecasters --> base
  autoregressive --> base
  module --> base
  step_predictors --> base
  graph --> base
  graph --> graph_lam
  graph --> hi_lam
  graph --> hi_lam_parallel
  graph --> hierarchical
  base --> base
  graph_lam --> base
  hi_lam --> hierarchical
  hi_lam_parallel --> hierarchical
  hierarchical --> base
